version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    volumes:
      - .:/var/www/app

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/app
      - ./nginx/ssl/cloudflare.crt:/etc/nginx/ssl/cloudflare.crt
      - ./nginx/ssl/cloudflare.key:/etc/nginx/ssl/cloudflare.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm

  redis:
    image: redis:alpine
    command: redis-server --requirepass pWUubVzZ8cz7tkhQ
    environment:
      REDIS_PASSWORD: pWUubVzZ8cz7tkhQ
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
